// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Data.Policia.Entities
{
    public partial class Juractuaciones
    {
        public short? Idexp { get; set; }
        public string Descripcion { get; set; }
        public DateTime? Fecha { get; set; }
        public string Ultima { get; set; }
        public decimal IdJuractuaciones { get; set; }

        public virtual Jurexpedientes IdexpNavigation { get; set; }
    }
}