// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Data.Policia.Entities
{
    public partial class Jurdocumentos
    {
        public short? Idexp { get; set; }
        public string Asunto { get; set; }
        public DateTime? Fecha { get; set; }
        public string Ruta { get; set; }
        public decimal IdJurdocumentos { get; set; }

        public virtual Jurexpedientes IdexpNavigation { get; set; }
    }
}