// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Data.Policia.Entities
{
    public partial class Jurestados
    {
        public Jurestados()
        {
            Jurexpedientes = new HashSet<Jurexpedientes>();
        }

        public decimal Idjurestado { get; set; }
        public string Estado { get; set; }

        public virtual ICollection<Jurexpedientes> Jurexpedientes { get; set; }
    }
}