// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Data.Policia.Entities
{
    public partial class Jurinteresados
    {
        public short IdJurinteresados { get; set; }
        public string Dem { get; set; }
        public string Nif { get; set; }
        public string Apenom { get; set; }
        public string Domicilio { get; set; }
        public short? Idexp { get; set; }
        public string Poblacion { get; set; }
        public string CodigoPostal { get; set; }
        public string Menor { get; set; }
        public string PadreMadreTutor { get; set; }

        public virtual Jurexpedientes IdexpNavigation { get; set; }
    }
}