// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Data.Policia.Entities
{
    public partial class Jurinhabiles
    {
        public DateTime? DiaInhabil { get; set; }
        public decimal IdJurinhabiles { get; set; }
    }
}