// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Data.Policia.Entities
{
    public partial class Jurmateria
    {
        public string Materia { get; set; }
        public decimal IdJurmateria { get; set; }
    }
}