// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Data.Policia.Entities
{
    public partial class Jurtramitacion
    {
        public short IdJurtramitacion { get; set; }
        public DateTime? FecInicioExp { get; set; }
        public DateTime? FecTeu1 { get; set; }
        public DateTime? FecPresentacionAlegaciones { get; set; }
        public DateTime? FecEnvioAlegacionesAgentes { get; set; }
        public DateTime? FecConstAlegacionesAgentes { get; set; }
        public DateTime? FecDiligPresenAlegAgentes { get; set; }
        public DateTime? FecPropuestaResolucion { get; set; }
        public DateTime? FecTeu2 { get; set; }
        public DateTime? FecAlegPropResolucion { get; set; }
        public DateTime? FecEnvioAlegInstructor { get; set; }
        public DateTime? FecContesAlegInstructor { get; set; }
        public DateTime? FecDiligPresenAlegInstruc { get; set; }
        public DateTime? FecResolucionExpediente { get; set; }
        public DateTime? FecTeu3 { get; set; }
        public DateTime? FecRecursoReposicion { get; set; }
        public DateTime? FecEnvioRentas { get; set; }
        public DateTime? FecCierreExpediente { get; set; }
        public short? Idexp { get; set; }
        public DateTime? FecNotificacionInicio { get; set; }
        public DateTime? FecNotificacionPropuesta { get; set; }
        public DateTime? FecNotificacionResolucion { get; set; }
        public DateTime? FecCobro { get; set; }

        public virtual Jurexpedientes IdexpNavigation { get; set; }
    }
}