// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Data.Policia.Entities
{
    public partial class Jurvencimientos
    {
        public short? Idexp { get; set; }
        public DateTime? Fecha { get; set; }
        public string Motivo { get; set; }
        public decimal IdJurvencimientos { get; set; }

        public virtual Jurexpedientes IdexpNavigation { get; set; }
    }
}