// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Data.Policia.Entities;

namespace Data.Policia.Context
{
    public partial class PoliciaContext : DbContext
    {
        public PoliciaContext()
        {
        }

        public PoliciaContext(DbContextOptions<PoliciaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Juractuaciones> Juractuaciones { get; set; }
        public virtual DbSet<Jurdocumentos> Jurdocumentos { get; set; }
        public virtual DbSet<Jurestados> Jurestados { get; set; }
        public virtual DbSet<Jurexpedientes> Jurexpedientes { get; set; }
        public virtual DbSet<Jurinhabiles> Jurinhabiles { get; set; }
        public virtual DbSet<Jurinteresados> Jurinteresados { get; set; }
        public virtual DbSet<Jurmateria> Jurmateria { get; set; }
        public virtual DbSet<Jurtramitacion> Jurtramitacion { get; set; }
        public virtual DbSet<Jurvencimientos> Jurvencimientos { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseOracle("Data Source=(DESCRIPTION =(ADDRESS=(PROTOCOL=TCP)(HOST= oraclescan)(PORT=1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = AYTOCC)(FAILOVER_MODE =(TYPE = SELECT)(METHOD = BASIC)(RETRIES = 180)(DELAY = 5))));User Id=MAKO;Password=MAmu,20.;Data Source=(DESCRIPTION =(ADDRESS=(PROTOCOL=TCP)(HOST= oraclescan)(PORT=1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = AYTOCC)(FAILOVER_MODE =(TYPE = SELECT)(METHOD = BASIC)(RETRIES = 180)(DELAY = 5))));User Id=POLICIA;Password=POia,08.;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("POLICIA");

            modelBuilder.Entity<Juractuaciones>(entity =>
            {
                entity.HasKey(e => e.IdJuractuaciones)
                    .HasName("SYS_C003531427");

                entity.ToTable("JURACTUACIONES");

                entity.Property(e => e.IdJuractuaciones)
                    .HasColumnType("NUMBER")
                    .HasColumnName("ID_JURACTUACIONES")
                    .HasDefaultValueSql("\"POLICIA\".\"SEQ_ID_JURACTUACIONES\".\"NEXTVAL\"");

                entity.Property(e => e.Descripcion)
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("DESCRIPCION");

                entity.Property(e => e.Fecha)
                    .HasColumnType("DATE")
                    .HasColumnName("FECHA");

                entity.Property(e => e.Idexp)
                    .HasColumnType("NUMBER(5,0)")
                    .HasColumnName("IDEXP");

                entity.Property(e => e.Ultima)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("ULTIMA");

                entity.HasOne(d => d.IdexpNavigation)
                    .WithMany(p => p.Juractuaciones)
                    .HasForeignKey(d => d.Idexp)
                    .HasConstraintName("SYS_C003531428");
            });

            modelBuilder.Entity<Jurdocumentos>(entity =>
            {
                entity.HasKey(e => e.IdJurdocumentos)
                    .HasName("SYS_C003531425");

                entity.ToTable("JURDOCUMENTOS");

                entity.Property(e => e.IdJurdocumentos)
                    .HasColumnType("NUMBER")
                    .HasColumnName("ID_JURDOCUMENTOS")
                    .HasDefaultValueSql("\"POLICIA\".\"SEQ_ID_JURDOCUMENTOS\".\"NEXTVAL\"");

                entity.Property(e => e.Asunto)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("ASUNTO");

                entity.Property(e => e.Fecha)
                    .HasColumnType("DATE")
                    .HasColumnName("FECHA");

                entity.Property(e => e.Idexp)
                    .HasColumnType("NUMBER(5,0)")
                    .HasColumnName("IDEXP");

                entity.Property(e => e.Ruta)
                    .HasMaxLength(300)
                    .IsUnicode(false)
                    .HasColumnName("RUTA");

                entity.HasOne(d => d.IdexpNavigation)
                    .WithMany(p => p.Jurdocumentos)
                    .HasForeignKey(d => d.Idexp)
                    .HasConstraintName("SYS_C003531426");
            });

            modelBuilder.Entity<Jurestados>(entity =>
            {
                entity.HasKey(e => e.Idjurestado)
                    .HasName("SYS_C003531432");

                entity.ToTable("JURESTADOS");

                entity.Property(e => e.Idjurestado)
                    .HasColumnType("NUMBER")
                    .HasColumnName("IDJURESTADO")
                    .HasDefaultValueSql("\"POLICIA\".\"SEQ_ID_JURESTADOS\".\"NEXTVAL\"");

                entity.Property(e => e.Estado)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ESTADO");
            });

            modelBuilder.Entity<Jurexpedientes>(entity =>
            {
                entity.HasKey(e => e.Idexp)
                    .HasName("JUREXPEDIENTES_PK");

                entity.ToTable("JUREXPEDIENTES");

                entity.Property(e => e.Idexp)
                    .HasColumnType("NUMBER(5,0)")
                    .HasColumnName("IDEXP")
                    .HasDefaultValueSql("\"POLICIA\".\"SEQ_ID_JUREXPEDIENTES\".\"NEXTVAL\"");

                entity.Property(e => e.Agentes)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("AGENTES");

                entity.Property(e => e.Auto)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("AUTO");

                entity.Property(e => e.CalificacionInfraccion)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("CALIFICACION_INFRACCION");

                entity.Property(e => e.DescripcionNoPecuniaria)
                    .HasMaxLength(1000)
                    .IsUnicode(false)
                    .HasColumnName("DESCRIPCION_NO_PECUNIARIA");

                entity.Property(e => e.Ejercicio)
                    .HasColumnType("NUMBER")
                    .HasColumnName("EJERCICIO");

                entity.Property(e => e.Estado)
                    .HasColumnType("NUMBER")
                    .HasColumnName("ESTADO");

                entity.Property(e => e.ExpedienteTao)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("EXPEDIENTE_TAO");

                entity.Property(e => e.FecDenuncia)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_DENUNCIA");

                entity.Property(e => e.Fecentrada)
                    .HasColumnType("DATE")
                    .HasColumnName("FECENTRADA");

                entity.Property(e => e.HechoDenunciado)
                    .HasMaxLength(250)
                    .IsUnicode(false)
                    .HasColumnName("HECHO_DENUNCIADO");

                entity.Property(e => e.HoraDenuncia)
                    .HasMaxLength(6)
                    .IsUnicode(false)
                    .HasColumnName("HORA_DENUNCIA");

                entity.Property(e => e.Importe)
                    .HasColumnType("NUMBER(8,2)")
                    .HasColumnName("IMPORTE");

                entity.Property(e => e.Importe20)
                    .HasColumnType("NUMBER(8,2)")
                    .HasColumnName("IMPORTE20");

                entity.Property(e => e.Importe40)
                    .HasColumnType("NUMBER(8,2)")
                    .HasColumnName("IMPORTE40");

                entity.Property(e => e.ImporteRecaudado)
                    .HasColumnType("NUMBER(8,2)")
                    .HasColumnName("IMPORTE_RECAUDADO");

                entity.Property(e => e.Lugar)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("LUGAR");

                entity.Property(e => e.Materia)
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasColumnName("MATERIA");

                entity.Property(e => e.Norma)
                    .HasMaxLength(1000)
                    .IsUnicode(false)
                    .HasColumnName("NORMA");

                entity.Property(e => e.Numexp)
                    .HasColumnType("NUMBER(5,0)")
                    .HasColumnName("NUMEXP");

                entity.Property(e => e.Observaciones)
                    .HasMaxLength(1700)
                    .IsUnicode(false)
                    .HasColumnName("OBSERVACIONES");

                entity.Property(e => e.PreceptoInfraccion)
                    .HasMaxLength(1000)
                    .IsUnicode(false)
                    .HasColumnName("PRECEPTO_INFRACCION");

                entity.Property(e => e.PreceptoSancion)
                    .HasMaxLength(1000)
                    .IsUnicode(false)
                    .HasColumnName("PRECEPTO_SANCION");

                entity.Property(e => e.SancionNoPecuniaria)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("SANCION_NO_PECUNIARIA")
                    .HasDefaultValueSql("'0' ");

                entity.Property(e => e.SancionPecuniaria)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("SANCION_PECUNIARIA")
                    .HasDefaultValueSql("'0' ");

                entity.HasOne(d => d.EstadoNavigation)
                    .WithMany(p => p.Jurexpedientes)
                    .HasForeignKey(d => d.Estado)
                    .HasConstraintName("SYS_C003532940");
            });

            modelBuilder.Entity<Jurinhabiles>(entity =>
            {
                entity.HasKey(e => e.IdJurinhabiles)
                    .HasName("SYS_C003568499");

                entity.ToTable("JURINHABILES");

                entity.Property(e => e.IdJurinhabiles)
                    .HasColumnType("NUMBER")
                    .HasColumnName("ID_JURINHABILES")
                    .HasDefaultValueSql("\"POLICIA\".\"SEQ_ID_JURINHABILES\".\"NEXTVAL\"");

                entity.Property(e => e.DiaInhabil)
                    .HasColumnType("DATE")
                    .HasColumnName("DIA_INHABIL");
            });

            modelBuilder.Entity<Jurinteresados>(entity =>
            {
                entity.HasKey(e => e.IdJurinteresados)
                    .HasName("SYS_C003531424");

                entity.ToTable("JURINTERESADOS");

                entity.Property(e => e.IdJurinteresados)
                    .HasColumnType("NUMBER(5,0)")
                    .HasColumnName("ID_JURINTERESADOS")
                    .HasDefaultValueSql("\"POLICIA\".\"SEQ_ID_JURINTERESADOS\".\"NEXTVAL\"");

                entity.Property(e => e.Apenom)
                    .HasMaxLength(1000)
                    .IsUnicode(false)
                    .HasColumnName("APENOM");

                entity.Property(e => e.CodigoPostal)
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("CODIGO_POSTAL");

                entity.Property(e => e.Dem)
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("DEM");

                entity.Property(e => e.Domicilio)
                    .HasMaxLength(150)
                    .IsUnicode(false)
                    .HasColumnName("DOMICILIO");

                entity.Property(e => e.Idexp)
                    .HasColumnType("NUMBER(5,0)")
                    .HasColumnName("IDEXP");

                entity.Property(e => e.Menor)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("MENOR")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.Nif)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("NIF");

                entity.Property(e => e.PadreMadreTutor)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("PADRE_MADRE_TUTOR")
                    .HasDefaultValueSql("0");

                entity.Property(e => e.Poblacion)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("POBLACION");

                entity.HasOne(d => d.IdexpNavigation)
                    .WithMany(p => p.Jurinteresados)
                    .HasForeignKey(d => d.Idexp)
                    .HasConstraintName("SYS_C003531423");
            });

            modelBuilder.Entity<Jurmateria>(entity =>
            {
                entity.HasKey(e => e.IdJurmateria)
                    .HasName("SYS_C003531433");

                entity.ToTable("JURMATERIA");

                entity.Property(e => e.IdJurmateria)
                    .HasColumnType("NUMBER")
                    .HasColumnName("ID_JURMATERIA")
                    .HasDefaultValueSql("\"POLICIA\".\"SEQ_ID_JURMATERIA\".\"NEXTVAL\"");

                entity.Property(e => e.Materia)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("MATERIA");
            });

            modelBuilder.Entity<Jurtramitacion>(entity =>
            {
                entity.HasKey(e => e.IdJurtramitacion)
                    .HasName("JURDENUNCIAS_PK");

                entity.ToTable("JURTRAMITACION");

                entity.Property(e => e.IdJurtramitacion)
                    .HasColumnType("NUMBER(5,0)")
                    .HasColumnName("ID_JURTRAMITACION")
                    .HasDefaultValueSql("\"POLICIA\".\"SEQ_ID_JURTRAMITACION\".\"NEXTVAL\"");

                entity.Property(e => e.FecAlegPropResolucion)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_ALEG_PROP_RESOLUCION");

                entity.Property(e => e.FecCierreExpediente)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_CIERRE_EXPEDIENTE");

                entity.Property(e => e.FecCobro)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_COBRO");

                entity.Property(e => e.FecConstAlegacionesAgentes)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_CONST_ALEGACIONES_AGENTES");

                entity.Property(e => e.FecContesAlegInstructor)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_CONTES_ALEG_INSTRUCTOR");

                entity.Property(e => e.FecDiligPresenAlegAgentes)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_DILIG_PRESEN_ALEG_AGENTES");

                entity.Property(e => e.FecDiligPresenAlegInstruc)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_DILIG_PRESEN_ALEG_INSTRUC");

                entity.Property(e => e.FecEnvioAlegInstructor)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_ENVIO_ALEG_INSTRUCTOR");

                entity.Property(e => e.FecEnvioAlegacionesAgentes)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_ENVIO_ALEGACIONES_AGENTES");

                entity.Property(e => e.FecEnvioRentas)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_ENVIO_RENTAS");

                entity.Property(e => e.FecInicioExp)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_INICIO_EXP");

                entity.Property(e => e.FecNotificacionInicio)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_NOTIFICACION_INICIO");

                entity.Property(e => e.FecNotificacionPropuesta)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_NOTIFICACION_PROPUESTA");

                entity.Property(e => e.FecNotificacionResolucion)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_NOTIFICACION_RESOLUCION");

                entity.Property(e => e.FecPresentacionAlegaciones)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_PRESENTACION_ALEGACIONES");

                entity.Property(e => e.FecPropuestaResolucion)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_PROPUESTA_RESOLUCION");

                entity.Property(e => e.FecRecursoReposicion)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_RECURSO_REPOSICION");

                entity.Property(e => e.FecResolucionExpediente)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_RESOLUCION_EXPEDIENTE");

                entity.Property(e => e.FecTeu1)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_TEU1");

                entity.Property(e => e.FecTeu2)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_TEU2");

                entity.Property(e => e.FecTeu3)
                    .HasColumnType("DATE")
                    .HasColumnName("FEC_TEU3");

                entity.Property(e => e.Idexp)
                    .HasColumnType("NUMBER(5,0)")
                    .HasColumnName("IDEXP")
                    .HasDefaultValueSql("\"POLICIA\".\"SEQ_ID_JUREXPEDIENTES\".\"CURRVAL\"");

                entity.HasOne(d => d.IdexpNavigation)
                    .WithMany(p => p.Jurtramitacion)
                    .HasForeignKey(d => d.Idexp)
                    .HasConstraintName("SYS_C003531422");
            });

            modelBuilder.Entity<Jurvencimientos>(entity =>
            {
                entity.HasKey(e => e.IdJurvencimientos)
                    .HasName("SYS_C003531430");

                entity.ToTable("JURVENCIMIENTOS");

                entity.Property(e => e.IdJurvencimientos)
                    .HasColumnType("NUMBER")
                    .HasColumnName("ID_JURVENCIMIENTOS")
                    .HasDefaultValueSql("\"POLICIA\".\"SEQ_ID_JURVENCIMIENTOS\".\"NEXTVAL\"");

                entity.Property(e => e.Fecha)
                    .HasColumnType("DATE")
                    .HasColumnName("FECHA");

                entity.Property(e => e.Idexp)
                    .HasColumnType("NUMBER(5,0)")
                    .HasColumnName("IDEXP");

                entity.Property(e => e.Motivo)
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("MOTIVO");

                entity.HasOne(d => d.IdexpNavigation)
                    .WithMany(p => p.Jurvencimientos)
                    .HasForeignKey(d => d.Idexp)
                    .HasConstraintName("SYS_C003531429");
            });

            modelBuilder.HasSequence("SEQ_ID_JURACTUACIONES");

            modelBuilder.HasSequence("SEQ_ID_JURDOCUMENTOS");

            modelBuilder.HasSequence("SEQ_ID_JURESTADOS");

            modelBuilder.HasSequence("SEQ_ID_JUREXPEDIENTES");

            modelBuilder.HasSequence("SEQ_ID_JURINHABILES");

            modelBuilder.HasSequence("SEQ_ID_JURINTERESADOS");

            modelBuilder.HasSequence("SEQ_ID_JURMATERIA");

            modelBuilder.HasSequence("SEQ_ID_JURTRAMITACION");

            modelBuilder.HasSequence("SEQ_ID_JURVENCIMIENTOS");

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}